- hosts: all
  become: yes
  tasks:
    - name: wait 300 seconds for port 22 to become open and contain "SSH" - then the SSH connection should work afterwards
      wait_for:
        port: 22
        search_regex: SSH
        delay: 5
        timeout: 300

    - name: setup containerd
      import_role:
        name: containerd

    - name: setup kubeadm
      import_role:
        name: kubeadm
