- hosts: all
  become: yes
  tasks:
    - name: setup containerd
      import_role:
        name: containerd

    - name: setup kubeadm
      import_role:
        name: kubeadm

- hosts: master_0
  become: yes
  tasks:
    - name: kubeadm init
      import_role:
        name: kubeadm_init

- hosts: worker
  become: yes
  tasks:
    - name: kubeadm join
      import_role:
        name: kubeadm_join
