- hosts: master_0
  become: yes
  tasks:
    - name: kubeadm init
      import_role:
        name: kubeadm_init

- hosts: worker
  become: yes
  tasks:
    - name: kubeadm join
      import_role:
        name: kubeadm_join
