- name: initialize the cluster with kubeadm
  become: true
  delegate_to: '{{ pulumi_info.k8s_master_0_public_ip }}'
  delegate_facts: true
  shell: |
    kubeadm init \
      --pod-network-cidr={{ pod_network_cidr }}/16 >> kubeadm_init.txt
  args:
    chdir: /home/{{ remote_user }}
    creates: kubeadm_init.txt

- name: create /home/{{ remote_user }}/.kube directory
  become: true
  delegate_to: '{{ pulumi_info.k8s_master_0_public_ip }}'
  delegate_facts: true
  file:
    path: /home/{{ remote_user }}/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to {{ remote_user }}'s kube config
  become: true
  delegate_to: '{{ pulumi_info.k8s_master_0_public_ip }}'
  delegate_facts: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ remote_user }}/.kube/config
    remote_src: yes
    mode: 0644
    owner: '{{ remote_user }}'
    group: '{{ remote_user }}'

- name: get token
  become: true
  delegate_to: '{{ pulumi_info.k8s_master_0_public_ip }}'
  delegate_facts: true
  command: kubeadm token list -o json
  register: kubeadm_token

- name: save token
  copy:
    dest: '{{ playbook_dir }}/k8s/kubeadm_token.json'
    content: '{{ kubeadm_token.stdout  }}'
    mode: 0644

- name: get hash
  become: true
  delegate_to: '{{ pulumi_info.k8s_master_0_public_ip }}'
  delegate_facts: true
  shell: |
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt \
    | openssl rsa -pubin -outform der 2>/dev/null \
    | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: kubeadm_hash

- name: save hash
  copy:
    dest: '{{ playbook_dir }}/k8s/kubeadm_hash.txt'
    content: '{{ kubeadm_hash.stdout }}'
    mode: 0644
