apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: # email
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            -  # "domain"
        dns01:
          cloudflare:
            email: # cloudflare email
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
