apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-autoscaler-autodiscover.yaml

patches:
  - path: patches/annotations.yaml
    target:
      kind: Deployment
      name: cluster-autoscaler
  - path: patches/command.yaml
    target:
      kind: Deployment
      name: cluster-autoscaler
