apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
type: Opaque
data:
  aws_access_key_id: <BASE64_OF_YOUR_AWS_ACCESS_KEY_ID>
  aws_secret_access_key: <BASE64_OF_YOUR_AWS_SECRET_ACCESS_KEY>
