namespaceOverride: monitoring
fullnameOverride: prometheus-operator
defaultRules:
  create: false
global:
  rbac:
    create: true
alertmanager:
  enabled: true
grafana:
  enabled: true
  namespaceOverride: monitoring
kubeApiserver:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: false
coreDns:
  enabled: true
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: true
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  namespaceOverride: monitoring
nodeExporter:
  enabled: true
prometheus-node-exporter:
  namespaceOverride: monitoring
prometheusOperator:
  enabled: true
  hostNetwork: true
  tls:
    enabled: false
prometheus:
  enabled: true
  thanosService:
    enabled: false
  prometheusSpec:
    retention: 10d
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: 20Gi
