---
- hosts: all
  become: yes
  tasks:
    - name: purge
      apt:
        name: '{{ item }}'
        state: absent
        update_cache: yes
      loop: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']

    - name: install required
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        [
          'apt-transport-https',
          'ca-certificates',
          'curl',
          'gnupg',
          'lsb-release',
        ]

    - name: add docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: add docker repository
      apt_repository:
        repo: deb
          [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        filename: docker

    - name: install docker
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: set cgroupdriver to systemd
      copy:
        dest: '/etc/docker/daemon.json'
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }

    - name: systemd enable docker
      ansible.builtin.systemd:
        name: '{{ item }}'
        enabled: yes
        state: restarted
      loop: ['docker', 'containerd']

    - name: systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: yes
